name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'URL for boot or recovery image'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        pip install twrpdtgen
        mkdir dt

    - name: Download boot or recovery img
      run: |
        aria2c ${{ github.event.inputs.IMG_URL }} -o boot.img
        ls -lh boot.img

    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ boot.img

    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: TWRP_Device_Tree-${{ github.run_id }}
        body: |
          Device Tree generated for TWRP
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
